### PR TITLE
preserve duplicate headers

### PR DESCRIPTION
**Pull request by yu-re-ka**
#103

### CODE REVIEW

**Comment by seanmonstar** [comment]
Nice catch! Think it'd be possible to include a unit test so we don't mess this up later?

**Comment by yu-re-ka** [comment]
End-to-end or just for the HeaderIter?

**Comment by yu-re-ka** [comment]
Added something, let be know if this is what you wanted

**Review by seanmonstar — APPROVED** [review]
Excellent, thank you!

**Pull request merged**
