### PR TITLE
Create a client example

### PR DESCRIPTION
**Pull request by seanmonstar**
This starts creating usable examples so we can start seeing it interact with other implementations.

### CODE REVIEW

**Comment by seanmonstar** [comment]
@stammw I got the ALPN fixed (needed `h3-29` instead of just `h3` for several servers), but so far, they all timeout after sending the request. I'm probably missing something obvious?

**Comment by seanmonstar** [comment]
Found the issue. After closing the send side, I also needed to add ignoring of unknown/reserved frames, and success!

**Comment by stammw** [comment]
It actually works! Nice ! :)

**Comment by seanmonstar** [comment]
I started adding printing of the received data too, and hit a panic `"There is still data to read, please call poll_data() ..."`...

**Comment by seanmonstar** [comment]
Ok, so I fixed that by making sure `recv_data` wouldn't poll for a new frame if `FrameStream::remaining_data != 0`. Now I'm hitting a panic in h3-quinn, advancing the buffer too far after calling `read_unordered()`.

**Comment by seanmonstar** [comment]
Ok, all set! `cargo run --example client https://blog.cloudflare.com` fetches the full page!

**Comment by stammw** [comment]
All right! Sorry I haven't been that much involved into this but the my shiny new embedded linux video driver with fpga-cuda interface thing job is taking a lot of bandwidth.

**Pull request merged**
