### PR TITLE
increase msrv to 1.70 like tokio

### PR DESCRIPTION
**Pull request by Ruben2424**

### CODE REVIEW

**Review by djc — APPROVED** [review]
Makes sense!

**Comment by seanmonstar** [comment]
Do we need anything from the newer Tokio? If not, we could just pin the Tokio version in the MSRV job. That's what I've done in hyper, h2, and reqwest.

**Comment by djc** [comment]
> Do we need anything from the newer Tokio? If not, we could just pin the Tokio version in the MSRV job. That's what I've done in hyper, h2, and reqwest.

For Quinn we've chosen (IIRC) to just adopt the Tokio MSRV, so that might constrain the choices here?

**Comment by Ruben2424** [comment]
Quinn has 1.70 msrv, so I guess h3-quinn will have to use the same.
if we want to support earlier versions for h3 we can change it back. But I would not complicate thinks now. 1.70 is over a year old and h3 is still in pre release.

**Pull request merged**
