### PR TITLE
Feed compliance report generator

### PR DESCRIPTION
**Pull request by eagr**
Redoing #117 
* fixed broken anchors in spec links
* corrected some dislocated annotations
* applied a new annotation type [IMPLICATION](https://github.com/awslabs/duvet/blob/681f2b02178b2f9b98439ab4d9ff745ebbdf2375/src/annotation.rs#L142) for requirements whose related code is self-evident

### CODE REVIEW

**Comment by eagr** [comment]
progress so far:
image

**Comment by seanmonstar** [comment]
Wonderful work!

**Comment by eagr** [comment]
Ready for review! @seanmonstar 

There are many spec requirements left not annotated.
* some are not applicable, like IANA registration requirements
* some are kind of out of scope, like downgrading to a TCP-based protocol when fail to establish a QUIC connection
* others could be annotated as TODOs, which should be placed where the missing implementations should go. I don't have a clear idea about that so I guess I should probably leave them to someone who knows better.

Kinda wish there would be some `opt-out` type in duvet so we could have more intuitive stats, like in terms of how many applicable requirements left to do.

**Comment by eagr** [comment]
Would you like to also bump the msrv in ci?

**Comment by seanmonstar** [comment]
I bumped the MSRV just now, if you wanna rebase.

**Comment by seanmonstar** [comment]
> some are not applicable, like IANA registration requirements

Do you have an example? I agree that likely we can skip these.

> some are kind of out of scope

Indeed, some are requirements that are at the application-level. Similar to how in the HTTP/2 spec, there's words about what to do if proxying HTTP/1 to HTTP/2, at the library level we can't know you're doing that. Should be fine to punt. Is there a decent way to do so?

Curious if @camshaft knows the best way we could signal that to duvet.

**Review by seanmonstar — APPROVED** [review]

**Comment by camshaft** [comment]
In s2n-quic we've used `exception` for things that don't apply to the library (like IANA registration requirements). I think it captures the nature of it, especially since you can give a reason for why it's an exception.

**Comment by eagr** [comment]
> Do you have an example? I agree that likely we can skip these.

https://www.rfc-editor.org/rfc/rfc9114#section-11.2.1

```
While this registry is separate from the "HTTP/2 Frame Type" registry
defined in [HTTP/2], it is preferable that the assignments parallel
each other where the code spaces overlap.  If an entry is present in
only one registry, every effort SHOULD be made to avoid assigning the
corresponding value to an unrelated operation.  Expert reviewers MAY
reject unrelated registrations that would conflict with the same
value in the corresponding registry.
```

> In s2n-quic we've used exception for things that don't apply to the library (like IANA registration requirements). I think it captures the nature of it, especially since you can give a reason for why it's an exception.

Thought about that too, but it didn't feel quite right. I guess I got too used to the concept of exception in programming. It kinda makes sense now. Thanks.

Say we proceed with using `type=exception`, where do you want to put the annotations in question? @seanmonstar @camshaft Since some of them have little connection with the code. They are basically just noises to the code base.

**Comment by camshaft** [comment]
We have an `exceptions` directory with toml files

Example: https://github.com/aws/s2n-quic/blob/main/specs/exceptions/rfc8899/6.2.1.3.toml

**Comment by eagr** [comment]
Oh, I see how this works, thanks! Will do it later in another pr.

Could we get this merged soon if it looks good? Kinda don't wanna linger over this for too long as there are many changes across the code base. Merge conflicts alert.

**Pull request merged**
