### PR TITLE
Grease Setting

### PR DESCRIPTION
**Pull request by Ruben2424**
Hi,

i tried to solve #28. I think the settings grease works.
But when should the frame and stream grease be sent?

### CODE REVIEW

**Review by seanmonstar — COMMENTED** [review]
- [Stream Grease](https://httpwg.org/specs/rfc9114.html#stream-grease) suggests to do it on an idle connection. [quiche](https://github.com/cloudflare/quiche/blob/4bda0917dd5aa535f39214063ee85c2cad00ceb2/quiche/src/h3/mod.rs#L906) does it immediately.
- [Frame Grease](https://httpwg.org/specs/rfc9114.html#frame-reserved) doesn't give a suggestion anymore, just that they *MAY* be sent on any stream. [quiche](https://github.com/cloudflare/quiche/blob/4bda0917dd5aa535f39214063ee85c2cad00ceb2/quiche/src/h3/mod.rs#L1054) seems to send a grease frame on the first request stream, as the first frame. It currently only does this once per connection.

We don't need to do it in exactly the same order as quiche does, in fact being slightly different is probably a good thing for the purpose of grease.

**Comment by seanmonstar** [comment]
Thanks so much for starting on this! I forgot to mention that in the review, but this is awesome <3

**Comment by Ruben2424** [comment]
Do you have any idea how to check whether a connection is idle? And when should the check happen?

**Comment by seanmonstar** [comment]
I've restarted the CI jobs a few times, thinking there was something racey, but now I'm wondering if they're noticing a difference in streams/frames received, since it seems they're tests expecting the connection to close in a certain way?

**Comment by Ruben2424** [comment]
Ok, i will see if i find the Problem. On my local machine the tests are successful with `rustc 1.62.1 `.

**Comment by Ruben2424** [comment]
ah now the tests are successful

**Review by seanmonstar — APPROVED** [review]
Awesome work!!

**Pull request merged**
